import { z } from 'zod';

/**
 * Common primitive types
 */
export const AgentIdSchema = z.string().describe("UUID or identifier of the agent");
export const TimestampSchema = z.string().datetime().describe("ISO 8601 timestamp");

/**
 * Instruction Schema (SIE)
 */
export const InstructionSchema = z.object({
    action: z.enum(["navigate", "click", "input", "extract", "noop"]),
    target: z.string().optional(),
    value: z.string().nullable().optional(),
    options: z.record(z.any()).optional(),
    meta: z.record(z.any()).optional(),
});

export type Instruction = z.infer<typeof InstructionSchema>;

/**
 * 1. Mission (The Quest)
 * The initial instruction provided by the Human (Quest Giver).
 */
export const MissionSchema = z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.string().describe("Detailed description of the task"),
    evaluation_prompt: z.string().describe("The criteria by which the solution will be judged. Dynamic Evaluation Criteria."),
    created_at: TimestampSchema,
    created_by: z.string().default("human"),
});

export type Mission = z.infer<typeof MissionSchema>;

/**
 * 2. Proposal (The Solution)
 * Generated by an Executor Agent.
 */
export const ProposalSchema = z.object({
    id: z.string().uuid(),
    mission_id: z.string().uuid(),
    author_id: AgentIdSchema,
    content: z.string().describe("The proposed solution (code, text, plan, etc.)"),
    reasoning: z.string().optional().describe("Explanation of why this solution was chosen"),
    instructions: z.array(InstructionSchema).optional().describe("Structured Instructions generated by agent for SIE execution"),
    metadata: z.record(z.any()).optional().describe("Agent metadata / Swarm meta"),
    created_at: TimestampSchema,
});

export type Proposal = z.infer<typeof ProposalSchema>;

/**
 * 3. Critique (The Review)
 * Generated by a Reviewer Agent (Peer Review).
 */
export const CritiqueSchema = z.object({
    id: z.string().uuid(),
    proposal_id: z.string().uuid(),
    reviewer_id: AgentIdSchema,
    feedback: z.string().describe("Detailed feedback on the proposal based on the Mission's evaluation_prompt"),
    score: z.number().min(0).max(100).describe("Numerical score (0-100)"),
    created_at: TimestampSchema,
});

export type Critique = z.infer<typeof CritiqueSchema>;

/**
 * 4. ScoreCard (The Verdict)
 * Automated aggregation or final decision.
 * In a pure swarm, this might be calculated from multiple Critiques.
 */
export const ScoreCardSchema = z.object({
    proposal_id: z.string().uuid(),
    mission_id: z.string().uuid(),
    average_score: z.number(),
    critique_count: z.number(),
    status: z.enum(["ACCEPTED", "REJECTED", "NEEDS_REVISION"]),
    final_comment: z.string().optional(),
});

export type ScoreCard = z.infer<typeof ScoreCardSchema>;

/**
 * Helper to build a Proposal from high-level mission + instruction list
 */
export function buildProposal(missionId: string, content: string, instructions: Instruction[] = [], metadata = {}): Partial<Proposal> {
    return {
        mission_id: missionId,
        content,
        instructions,
        metadata
    };
}
